### ISSUE TITLE
RegisterPlayerEvent _ON_KILLED_BY_CREATURE

### ISSUE THREAD

**Issue by betayi** [ElunaLuaEngine/Eluna#451] opened 2023-10-29 03:34 UTC
PLAYER_EVENT_ON_KILLED_BY_CREATURE      =     8,

It seems not triggered ( not print ) while player killed by creature
--[code example]--
function OnPlayerDie(event, killer, killed)
  print(killed:GetName().." killed")
end

RegisterPlayerEvent(8, OnPlayerDie)

other RegisterPlayerEvent works fine
at cmangostbc with LuaEngine@f8f97c55f79a7563c29b0a7c917babef96cdbe0c

**Comment by Niam5** [comment] 2023-10-31 15:55
The core your having this issue with is CMaNGOS TBC right? If so ill look at since I'm the maintainer for those.

**Comment by Niam5** [comment] 2023-11-01 04:02
Please update your source files to 5279f5709d4a75f1a32bfe3e9411367a7feb7bb6 and retest for me please.

**Comment by betayi** [comment] 2023-11-01 23:37
yes, it works,tyvm!

**Comment by betayi** [comment] 2023-11-10 15:10
this will make a core crash in sometimes #452

**Comment by Niam5** [comment] 2023-11-22 02:55
Duplicate of #452

**Closed by Niam5** 2023-11-22 02:55 UTC
