### ISSUE TITLE
Eluna Running and reloading on Multiple maps causing issues

### ISSUE THREAD

**Issue by JadaDev** [ElunaLuaEngine/Eluna#485] opened 2024-07-05 16:16 UTC
When i use reload Eluna it actually reloads on all maps i understand that but -1 should be all maps, 

![image](https://github.com/ElunaLuaEngine/Eluna/assets/9011541/6879c558-945e-4eec-a83e-0697e3960c95)

Now my problem is i wrote normal script and it's running multiple times : 

![image](https://github.com/ElunaLuaEngine/Eluna/assets/9011541/a755fe06-d316-462f-9c1f-a19e53110d8d)

Simple Script : 

```
-- Simple server time announcing.

local eachmsec = 60000

local function AnnounceServerTime(eventId, delay, repeats)
    local currentTime = GetGameTime()
    local hours = math.floor(currentTime / 3600) % 24
    local minutes = math.floor(currentTime / 60) % 60
    local ampm = "AM"
    if hours >= 12 then
        ampm = "PM"
    end
    if hours > 12 then
        hours = hours - 12
    elseif hours == 0 then
        hours = 12
    end
    local timeString = string.format("%02d:%02d %s", hours, minutes, ampm)
    SendWorldMessage("Server Time: " .. timeString)
end

CreateLuaEvent(AnnounceServerTime, eachmsec, 0)

```

**Comment by Foereaper** [comment] 2024-07-06 09:48
That's as expected. Each map has its own Lua state, and each state runs every script that is considered global.

If you want a script to only run on a specific map, put it in a subdirectory prefixed with the map id. If you only want it to run in the global state, add the following to the top of the script.

`-- Do not load for the global state
if(GetStateMapId() ~= -1) then return; end`

If you want it to run on all states except the global state, then reverse the logic and do ==.

**Comment by JadaDev** [comment] 2024-07-10 10:45
That wasn't the case before, why this change all of sudden ?

**Comment by Foereaper** [comment] 2024-07-10 11:34
I imagine you didn't intend to close the issue, so I'll reopen it.

From July 1st we've officially switched from the old, single state implementation to multistate by default. What multistate is, is explained in length on our discord server. I'm not sure of you're a member there or not, but it's in the announcement channel.

I'm short, multistate has unique Lua states per map for pretty large performance reasons. The old single state scheme forced emulators to run single threaded, which is pretty bad. Some scripts therefore need to be adjusted to work as intended with multistate.

**Closed** 2024-07-16 15:18 UTC
