### ISSUE TITLE
fatal error LNK1181: cannot open input file 'LuaEngine.lib'

### ISSUE THREAD

**Issue by Talan2015** [ElunaLuaEngine/Eluna#149] opened 2015-03-11 20:22 UTC
Using pre-merged WOTLK files, tried to compile and just getting
fatal error LNK1181: cannot open input file 'LuaEngine.lib'

**Comment by Foereaper** [comment] 2015-03-11 20:27
How did you clone the repo? And what source did you use? What errors caused the engine not to compile?

**Comment by Talan2015** [comment] 2015-03-11 20:37
That error is all that's in my error list, downloaded https://github.com/ElunaLuaEngine/ElunaMangosWotlk in zip format,

**Comment by Foereaper** [comment] 2015-03-11 20:43
The zip does not includes submodules, namely Eluna. You'll have to clone it through git using recursive:

"git clone https://github.com/ElunaLuaEngine/ElunaMangosWotlk.git --recursive"

The recursive tag will automatically pull in the Lua engine source files.

**Comment by Talan2015** [comment] 2015-03-11 20:47
Sorry, I linked the wrong one, I'm using TC not mangos

**Comment by Foereaper** [comment] 2015-03-11 20:48
Hehe alright. The same still applies though, you'll have to clone using git, as Github's rar downloads do not include submodules unfortunately.

**Comment by Talan2015** [comment] 2015-03-11 20:54
Alright, cloning now.

**Comment by Talan2015** [comment] 2015-03-11 21:27
Now I'm getting other errors, would you be able to help me and add me on skype please? Talan-Legacy, I want to explain in-depth what's going on.

**Comment by Easelm** [comment] 2015-03-11 21:52
What are the errors? Would be helpful if you pasted them. If you want to receive more help, post in Eluna Support on EmuDevs: http://emudevs.com/forumdisplay.php/280-Engine

**Comment by Foereaper** [comment] 2015-03-11 21:58
As per correspondence with Rochet on the above matter, the issue is not related to Eluna. Closing.

**Closed by Foereaper** 2015-03-11 21:58 UTC
